- id: detect-missing-init
  name: 'Detect missing __init__.py'
  description: 'Detect and optionally create __init__.py files'
  entry: detect-missing-init
  language: python
  always_run: true
  require_serial: true
  files: '.*.py'
