name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry add pre-commit pytest pytest-cov
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
      - name: Test with pytest
        run: |
          python -m py.test tests/ --cov=hook --cov-report term-missing
